import { createSystem, defaultConfig, defineConfig } from "@chakra-ui/react"

const config = defineConfig({
  theme: {
    tokens: {
      colors: {
        // ── Primitives ──────────────────────────────────────────────────────
        green: {
          50:  { value: "#F1FFE5" },
          100: { value: "#DDFBC6" },
          200: { value: "#BBF0BB" },
          300: { value: "#95E5A1" },
          400: { value: "#5AC792" },
          500: { value: "#009D7B" },
          600: { value: "#017B68" },
          700: { value: "#016F60" },
          800: { value: "#026257" },
          900: { value: "#014039" },
        },
        red: {
          50:  { value: "#FFF6F2" },
          100: { value: "#FFE8E0" },
          200: { value: "#FCC7B4" },
          300: { value: "#EFA287" },
          400: { value: "#E67E59" },
          500: { value: "#C84F25" },
          600: { value: "#A64929" },
          700: { value: "#814530" },
          800: { value: "#673014" },
          900: { value: "#591A04" },
        },
        yellow: {
          50:  { value: "#FFFAE2" },
          100: { value: "#FFF6CA" },
          200: { value: "#FFEFA1" },
          300: { value: "#FFE88C" },
          400: { value: "#FFDA68" },
          500: { value: "#EBC347" },
          600: { value: "#E1AA36" },
          700: { value: "#C28A12" },
          800: { value: "#8B6005" },
          900: { value: "#624200" },
        },
        teal: {
          50:  { value: "#F5F9FA" },
          100: { value: "#EEF5F7" },
          200: { value: "#D6ECF3" },
          300: { value: "#A4CEDB" },
          400: { value: "#82B8C7" },
          500: { value: "#578E9E" },
          600: { value: "#367F94" },
          700: { value: "#20697E" },
          800: { value: "#0D5266" },
          900: { value: "#032833" },
        },
        blue: {
          50:  { value: "#EBF8FF" },
          100: { value: "#BEE3F8" },
          200: { value: "#90CDF4" },
          300: { value: "#63B3ED" },
          400: { value: "#4299E1" },
          500: { value: "#3182CE" },
          600: { value: "#2B6CB0" },
          700: { value: "#2C5282" },
          800: { value: "#2A4365" },
          900: { value: "#1A365D" },
        },
        purple: {
          50:  { value: "#EFEDFD" },
          100: { value: "#E2DEF7" },
          200: { value: "#D4CFF1" },
          300: { value: "#BFB6DF" },
          400: { value: "#9789C5" },
          500: { value: "#7A6FA1" },
          600: { value: "#56488B" },
          700: { value: "#352471" },
          800: { value: "#251758" },
          900: { value: "#0F0533" },
        },
        slate: {
          50:  { value: "#F6F7FF" },
          100: { value: "#F0F1F9" },
          200: { value: "#D8D9E5" },
          300: { value: "#BCC0D1" },
          400: { value: "#9A9FB8" },
          500: { value: "#7C8094" },
          600: { value: "#6B6F8C" },
          700: { value: "#575B73" },
          800: { value: "#424559" },
          900: { value: "#1F2233" },
        },
        grey: {
          50:  { value: "#F8F9F9" },
          100: { value: "#E2E7E9" },
          200: { value: "#BFC2C8" },
          300: { value: "#A0A4AD" },
          400: { value: "#838894" },
          500: { value: "#666C7A" },
          600: { value: "#505660" },
          700: { value: "#454953" },
          800: { value: "#3A3E46" },
          900: { value: "#2C2E34" },
        },
        neutrals: {
          50:  { value: "#F8F9F9" },
          100: { value: "#EAE8E5" },
          200: { value: "#DAD8D2" },
          300: { value: "#C7C4C0" },
          400: { value: "#B1ADA7" },
          500: { value: "#8F8B87" },
          600: { value: "#77736F" },
          700: { value: "#696560" },
          800: { value: "#524E49" },
          900: { value: "#3E3B36" },
        },
        lime: {
          50:  { value: "#FAFFCC" },
          100: { value: "#F7FAA2" },
          200: { value: "#F0F56E" },
          300: { value: "#E1E55D" },
          400: { value: "#CCD12F" },
          500: { value: "#ADB219" },
          600: { value: "#949912" },
          700: { value: "#7C8009" },
          800: { value: "#565901" },
          900: { value: "#313300" },
        },
        mocha: {
          50:  { value: "#FAF9F7" },
          100: { value: "#F6F4F1" },
          200: { value: "#EBE5DF" },
          300: { value: "#D9CFC7" },
          400: { value: "#CCA38F" },
          500: { value: "#BB8670" },
          600: { value: "#B47056" },
          700: { value: "#895945" },
          800: { value: "#613623" },
          900: { value: "#442113" },
        },
        white: { value: "#ffffff" },
        black: { value: "#000000" },
      },

      // ── Spacing (4px grid — mirrors Figma spacing/* variables) ────────────────
      spacing: {
        "0":   { value: "0px"  },
        "0.5": { value: "2px"  },
        "1":   { value: "4px"  },
        "1.5": { value: "6px"  },
        "2":   { value: "8px"  },
        "2.5": { value: "10px" },
        "3":   { value: "12px" },
        "3.5": { value: "14px" },
        "4":   { value: "16px" },
        "5":   { value: "20px" },
        "6":   { value: "24px" },
        "7":   { value: "28px" },
        "8":   { value: "32px" },
        "10":  { value: "40px" },
        "12":  { value: "48px" },
        "14":  { value: "56px" },
        "16":  { value: "64px" },
      },

      shadows: {
        sm: { value: "2px 2px 3px 0 rgba(13, 82, 102, 0.1)" },
        md: { value: "0 0 10px 0 rgba(13, 82, 102, 0.1)" },
        lg: { value: "0 0 20px 0 rgba(13, 82, 102, 0.15)" },
      },
    },

    semanticTokens: {
      colors: {
        // ── Brand ────────────────────────────────────────────────────────────
        "brand.primary.50":  { value: "{colors.green.50}" },
        "brand.primary.100": { value: "{colors.green.100}" },
        "brand.primary.200": { value: "{colors.green.200}" },
        "brand.primary.300": { value: "{colors.green.300}" },
        "brand.primary.400": { value: "{colors.green.400}" },
        "brand.primary.500": { value: "{colors.green.500}" },
        "brand.primary.600": { value: "{colors.green.600}" },
        "brand.primary.700": { value: "{colors.green.700}" },
        "brand.primary.800": { value: "{colors.green.800}" },
        "brand.primary.900": { value: "{colors.green.900}" },

        "brand.secondary.50":  { value: "{colors.slate.50}" },
        "brand.secondary.100": { value: "{colors.slate.100}" },
        "brand.secondary.200": { value: "{colors.slate.200}" },
        "brand.secondary.300": { value: "{colors.slate.300}" },
        "brand.secondary.400": { value: "{colors.slate.400}" },
        "brand.secondary.500": { value: "{colors.slate.500}" },
        "brand.secondary.600": { value: "{colors.slate.600}" },
        "brand.secondary.700": { value: "{colors.slate.700}" },
        "brand.secondary.800": { value: "{colors.slate.800}" },
        "brand.secondary.900": { value: "{colors.slate.900}" },

        // ── Canvas ───────────────────────────────────────────────────────────
        "canvas.default":      { value: "{colors.neutrals.50}" },
        "canvas.alt":          { value: "{colors.teal.50}" },
        "canvas.backdrop":     { value: "{colors.grey.100}" },
        "canvas.brand-subtle": { value: "{colors.green.50}" },
        "canvas.modal":        { value: "{colors.white}" },

        // ── Content — light ──────────────────────────────────────────────────
        "content.light.default":      { value: "{colors.slate.800}" },
        "content.light.strong":       { value: "{colors.black}" },
        "content.light.medium":       { value: "{colors.slate.600}" },
        "content.light.subtle":       { value: "{colors.slate.500}" },
        "content.light.brand-strong": { value: "{colors.green.800}" },
        "content.light.brand-subtle": { value: "{colors.green.600}" },

        // ── Content — dark ───────────────────────────────────────────────────
        "content.dark.default":       { value: "{colors.slate.50}" },
        "content.dark.strong":        { value: "{colors.white}" },
        "content.dark.medium":        { value: "{colors.slate.500}" },
        "content.dark.subtle":        { value: "{colors.slate.300}" },
        "content.dark.brand-strong":  { value: "{colors.green.400}" },
        "content.dark.brand-subtle":  { value: "{colors.green.100}" },

        // ── Interaction ──────────────────────────────────────────────────────
        "interaction.main.default": { value: "{colors.green.800}" },
        "interaction.main.hover":   { value: "{colors.green.600}" },
        "interaction.main.active":  { value: "{colors.green.900}" },

        "interaction.muted.default": { value: "{colors.green.100}" },
        "interaction.muted.hover":   { value: "{colors.green.200}" },
        "interaction.muted.active":  { value: "{colors.green.100}" },

        "interaction.neutral.default":  { value: "{colors.slate.100}" },
        "interaction.neutral.hover":    { value: "{colors.slate.200}" },
        "interaction.neutral.active":   { value: "{colors.slate.300}" },
        "interaction.neutral.active-2": { value: "{colors.slate.100}" },

        "interaction.success.default": { value: "{colors.green.500}" },
        "interaction.success.hover":   { value: "{colors.green.400}" },
        "interaction.success.active":  { value: "{colors.green.600}" },

        "interaction.critical.default": { value: "{colors.red.500}" },
        "interaction.critical.hover":   { value: "{colors.red.400}" },
        "interaction.critical.active":  { value: "{colors.red.600}" },

        "interaction.info.default": { value: "{colors.blue.500}" },
        "interaction.info.hover":   { value: "{colors.blue.600}" },
        "interaction.info.active":  { value: "{colors.blue.700}" },

        "interaction.links.default":         { value: "{colors.green.500}" },
        "interaction.links.hover":           { value: "{colors.green.600}" },
        "interaction.links.neutral-default": { value: "{colors.slate.700}" },
        "interaction.links.neutral-hover":   { value: "{colors.slate.900}" },

        // ── Feedback ─────────────────────────────────────────────────────────
        "feedback.info.default":     { value: "{colors.blue.500}" },
        "feedback.info.subtle":      { value: "{colors.blue.50}" },
        "feedback.info.strong":      { value: "{colors.blue.600}" },
        "feedback.warning.default":  { value: "{colors.yellow.400}" },
        "feedback.warning.subtle":   { value: "{colors.yellow.50}" },
        "feedback.warning.strong":   { value: "{colors.yellow.800}" },
        "feedback.success.default":  { value: "{colors.green.500}" },
        "feedback.success.subtle":   { value: "{colors.green.50}" },
        "feedback.success.strong":   { value: "{colors.green.700}" },
        "feedback.critical.default": { value: "{colors.red.500}" },
        "feedback.critical.subtle":  { value: "{colors.red.100}" },
        "feedback.critical.strong":  { value: "{colors.red.600}" },

        "feedback.disabled.bg":     { value: "{colors.grey.100}" },
        "feedback.disabled.medium": { value: "{colors.grey.200}" },
        "feedback.disabled.strong": { value: "{colors.grey.400}" },

        // ── Interaction support ──────────────────────────────────────────────
        "interaction.support.disabled-bg": { value: "#EDEDED" },
        "interaction.support.disabled":    { value: "{colors.grey.200}" },

        // ── Focus ────────────────────────────────────────────────────────────
        "focus.brand-default":    { value: "{colors.green.500}" },
        "focus.brand-subtle":     { value: "{colors.green.100}" },
        "focus.neutral-subtle":   { value: "{colors.slate.300}" },
        "focus.neutral-default":  { value: "{colors.slate.500}" },
        "focus.alt":              { value: "{colors.teal.500}" },

        // ── Border ───────────────────────────────────────────────────────────
        "border.subtle": { value: "{colors.slate.400}" },
        "border.medium": { value: "{colors.slate.500}" },
        "border.strong": { value: "{colors.slate.800}" },

        // ── Avatar component ─────────────────────────────────────────────────
        "avatar.strong.default":  { value: "{colors.teal.600}" },
        "avatar.strong.hover":    { value: "{colors.teal.500}" },
        "avatar.strong.active":   { value: "{colors.teal.700}" },
        "avatar.strong.ring":     { value: "{colors.teal.700}" },
        "avatar.subtle.default":  { value: "{colors.green.100}" },
        "avatar.subtle.hover":    { value: "{colors.green.200}" },
        "avatar.subtle.active":   { value: "{colors.green.300}" },
        "avatar.subtle.ring":     { value: "{colors.slate.300}" },
        "avatar.neutral.default": { value: "{colors.slate.500}" },
        "avatar.neutral.hover":   { value: "{colors.slate.400}" },
        "avatar.neutral.active":  { value: "{colors.slate.600}" },
        "avatar.neutral.ring":    { value: "{colors.slate.600}" },
        "avatar.purple.default":  { value: "{colors.purple.600}" },
        "avatar.purple.hover":    { value: "{colors.purple.500}" },
        "avatar.purple.active":   { value: "{colors.purple.700}" },
        "avatar.purple.ring":     { value: "{colors.purple.700}" },
        "avatar.green.default":   { value: "{colors.green.800}" },
        "avatar.green.hover":     { value: "{colors.green.700}" },
        "avatar.green.active":    { value: "{colors.green.900}" },
        "avatar.green.ring":      { value: "{colors.green.900}" },
        "avatar.mocha.default":   { value: "{colors.mocha.700}" },
        "avatar.mocha.hover":     { value: "{colors.mocha.600}" },
        "avatar.mocha.active":    { value: "{colors.mocha.800}" },
        "avatar.mocha.ring":      { value: "{colors.mocha.800}" },
        "avatar.blue.default":    { value: "{colors.blue.600}" },
        "avatar.blue.hover":      { value: "{colors.blue.500}" },
        "avatar.blue.active":     { value: "{colors.blue.700}" },
        "avatar.blue.ring":       { value: "{colors.blue.700}" },
      },
    },
  },
})

export const system = createSystem(defaultConfig, config)
